#!/bin/bash

runcode()
{
	: '
        Args:
	    	$1 part
	    	$2 train data
	    	$3 test data
	    	$4 output file
    '
	python $1 $2 $3 $4
}

main()
{
    main_dir=`pwd`
    # Run Q1
	runcode  assign_2_2$1.py $2 $3 $4 
}

main $1 $2 $3 $4